### PR TITLE
Update for windows compability

### PR DESCRIPTION
**Pull request by Nojahhh**

### CODE REVIEW

**Comment by Nojahhh** [comment]
This PR includes the bug-fix related to image encoding which is already present in #31 

Let me know if you want me to redo this PR without it.

**Comment by a-r-r-o-w** [comment]
Thanks for the awesome work and helping this run on Windows! Many more folks should be able to run it now :)

I think it's okay to have the image.permute part. Could you revert the last commit?

**Comment by Nojahhh** [comment]
You're welcome! I'm just happy to help and appreciate the work you do for the community.

I reverted the changes and think this PR is ready for merge. Let me know if there is anything else I can assist with in future updates!

**Review by a-r-r-o-w — APPROVED** [review]
Thank you! I'll propagate the changes to other files

cc @sayakpaul

**Pull request merged**
