### PR TITLE
fix: resuming from a checkpoint when using deepspeed.

### PR DESCRIPTION
**Pull request by sayakpaul**
Fixes https://github.com/a-r-r-o-w/cogvideox-factory/issues/29 and some other things.

### CODE REVIEW

**Comment by sayakpaul** [comment]
@a-r-r-o-w, could you try to help me validate the changes by doing a complete experiment?

**Comment by a-r-r-o-w** [comment]
Sure, will do. Thanks for the PR!

**Comment by a-r-r-o-w** [comment]
I've verified that the loading/saving checkpoints works correctly on a small run. Will run a larger steps run now. Could you undo changes to `training/prepare_dataset.py` since it's been completely rewritten now?

**Comment by a-r-r-o-w** [comment]
DGX lost power (mentioned in the Slack channel) so the experiment got killed. Will restart now

**Comment by a-r-r-o-w** [comment]
@sayakpaul Here's a full experiment with DeepSpeed training: https://wandb.ai/aryanvs/cogvideox-lora/runs/565k2ach?nw=nwuseraryanvs

1000 steps, batch size 4, validated that saving and loading checkpoints works as expected.

I think good to merge. Could you propagate the DeepSpeed changes to other scripts too?

**Comment by sayakpaul** [comment]
@a-r-r-o-w ready for review.

**Review by a-r-r-o-w — APPROVED** [review]
thanks, looks great and works!

**Pull request merged**
